config/routes.rb
Rails.application.routes.draw do

  resources :locations
  resources :routes
  resources :users
  resources :attempts

  resources :sessions, only: [:new, :create, :destroy] 

  root 'sessions#new'
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
	belongs_to :user
	belongs_to :route
	validates :date_attempted, presence: true

	scope :this_day, -> {where('date_attempted = ?' , Date.today)}
	scope :this_week, -> {where('date_attempted > ?', 7.days.ago)}
	scope :this_month, -> {where('date_attempted > ? ',   30.days.ago)}
	scope :this_year, -> {where('date_attempted > ? ',   365.days.ago)}

	def add_modifiers(grade, completed, flash)
	
			if completed == true
				if flash == true
						grade *= 1.5
				else
					grade
				end
			else
				grade *= 0.25
			end
			grade
		end

	
end






		

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :routes
	
end

app/models/route.rb
class Route < ActiveRecord::Base
	belongs_to :location
	has_many :attempts


	def calculate_grade(level, modifier)
	@grade = level + 1
	if modifier == 1
			@grade +=  0.3333333
		elsif modifier == 2
			@grade -=  0.3333333
		else
			@grade 
		end
		@grade *= 10
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :attempts
	# has_many :routes, through :attempts
	validates :name, presence: true
	validates_presence_of :contact
	validates_uniqueness_of :contact
	has_secure_password
	mount_uploader :user_photo, UserPhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user 

  private

  def current_user
  	current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in				
  	if current_user.nil?
  		redirect_to login_path
  	end
  end

 
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
	def index
		@attempts = Attempt.all
	end

	def new
		@new_attempt = Attempt.new
	end

	def create
		@new_attempt = Attempt.new(attempt_params)
		grade = @new_attempt.route.score
	
		completed = @new_attempt.completed
			
		flash = @new_attempt.flash
		
		@new_attempt.attempt_score = @new_attempt.add_modifiers(grade, completed, flash)

		if @new_attempt.save
			redirect_to attempts_path
		else
			redirect_to new_attempt_path
		end
	end

	def show
		@attempt = Attempt.find(params[:id])
	end

	def edit
		@attempt = Attempt.find(params[:id])
	end

	def update
		@attempt = Attempt.find(params[:id])
		if @attempt.update_attributes(attempt_params)
			redirect_to attempts_path
		else
			redirect_to edit_attempts_path
		end
	end

	def destroy
		@attempt = Attempt.find(params[:id])
		@attempt.destroy
		redirect_to attempts_path
	end


private

 def attempt_params
 	params.require(:attempt).permit!
 end
 	
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	
	def index
		@locations = Location.all		
	end

	def new
		@new_location = Location.new
	end

	def create
		@new_location = Location.new(location_params)
		if @new_location.save
			redirect_to locations_path
		else
			redirect_to new_location_path
		end
	end

	def show
		@location = Location.find(params[:id])
	end

	def edit
		@location = Location.find(params[:id])
	end

	def update
		@location = Location.find(params[:id])
		if @location.update_attributes(location_params)
			redirect_to locations_path
		else
			redirect_to edit_locations_path
		end
	end

	def destroy
		@location = Location.find(params[:id])
		@location.delete
		redirect_to locations_path
	end

	private

	def location_params
		params.require(:location).permit(:name, :camping, :rock_type, :description, :area)
	end

	
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
	def index
		@routes = Route.all
	end

	def new
		@new_route = Route.new
	end

	def create
		@new_route = Route.new(route_params)
		@new_route.score = @new_route.calculate_grade(@new_route.grade, @new_route.modifier)
	
		if @new_route.save
			redirect_to routes_path
		else
			redirect_to new_route_path
		end
	end

	def show
		@route = Route.find(params[:id])
	end

	def edit
		@route = Route.find(params[:id])
	end

	def update
		@route = Route.find(params[:id])
		if @route.update_attributes(route_params)
			redirect_to routes_path
		else
			redirect_to edit_routes_path
		end
	end

	def destroy
		@route = Route.find(params[:id])
		@route.destroy
		redirect_to routes_path
	end


private

 def route_params
 	params.require(:route).permit(:name, :grade, :beta, :modifier , :location_id)
 end
 	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end


def create
 		
 		user = User.find_by_contact(params[:contact]).try(:authenticate, params[:password])  
 		if user 																									
 			session[:user_id] = user.id
 			redirect_to user_path(user.id), notice: "logged in"
 		else
 			flash.now.alert = "invalid email or pw"
 			render :new
 		end
 	end

 	def destroy
 		session[:user_id] =nil
 		redirect_to login_path, notice: "You logged out"
 	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
		@users = User.all
	end

	def new
		@new_user = User.new
	end

	def create
		@new_user = User.new(user_params)
		if @new_user.save
			redirect_to users_path
		else
			redirect_to new_user_path
		end
	end

	def show
		@user = User.find(params[:id])
	
		@attempts = Attempt.where('user_id = ?' , @user.id)

	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to users_path
		else
			redirect_to edit_users_path
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end


private

 def user_params
 	params.require(:user).permit!
end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def grade_format(grade, modifier)
		if modifier == 1
			value = "+"
		elsif modifier == 2
			value = "-"
		else
			value = ""
		end
		return "V#{grade}#{value}"
	end		

	def show_name(name)
		user = User.find(name)
		user.name

	end		

	def formatted_date(date)
		date.strftime("%B %-d, %Y")
	end

end

app/helpers/attempts_helper.rb
module AttemptsHelper





end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attempts/index.html.haml
.container
	=link_to "add a attempt", new_attempt_path
	%table.table-bordered.table-striped
		%th date
		%th attempt score
		%th notes
		%th name
		- @attempts.each do |f|
			%tr
				%td
					=formatted_date(f.date_attempted)
				%td
					=f.attempt_score
				%td
					=f.notes
				%td
					-if f.user
						=f.user.name

app/views/attempts/new.html.haml
= form_for @new_attempt, url: attempts_path do |f|
	/ User:
	/ = f.select :user_id, User.all.collect {|u| [u.name, u.id]}
	
	= f.hidden_field :user_id, :value => session[:user_id]
	= f.label :date_attempted
	= f.date_field :date_attempted
	Route
	= f.select :route_id, Route.all.collect {|u| ["#{u.name}, #{grade_format(u.grade,u.modifier)}", u.id]}


	=f.label :flash
	=f.check_box :flash

	=f.label :completed
	=f.check_box :completed

	=f.label :notes
	=f.text_area :notes

	=f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RockClimbing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= nav_bar :float => :top, :brand => "RockClimber", :responsive => true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_divider %>
        <%= drop_down "Menu" do %>
            <%= menu_item "Routes", routes_path %>
            <%= menu_item "Location", locations_path %>
            <%= menu_item "Attempts", attempts_path %>
            <%= menu_item "Users", users_path %>
          
        <% end %>
        	<%if current_user %>
        		<%= menu_item "Currently logged in as #{show_name(session[:user_id])}", user_path(session[:user_id]) %>
        		<% end %>
    <% end %>
    <%= menu_group :pull => :right do %>
        <% if current_user %>
            <%= menu_item "Log Out", logout_path %>
        <% else %>
            <%= menu_item "Log In", login_path %>
        <% end %>
    <% end %>
<% end %>




<%= yield %>

</body>
</html>

app/views/locations/_locations.html.haml
= f.label :name
%br
= f.text_field :name
%br
= f.label :description
%br
= f.text_area :description
%br
= f.label :camping
= f.check_box :camping
%br
= f.label :rock_type
= f.text_field :rock_type
%br
Location
= f.text_area :area
%br
= f.submit

app/views/locations/edit.html.haml
= form_for @location, url: location_path do |f|
	= render "locations", f: f

app/views/locations/index.html.haml
%h1 Locations
- @locations.each do |l|
	= l.name
	%br
	= l.description
	%br
	= l.camping
	%br
	= l.rock_type
	%br
	= l.area
	%br
	%br


=link_to "add a location", new_location_path

app/views/locations/new.html.haml
= form_for @new_location, url: locations_path do |f|
	= render "locations", f: f

app/views/locations/show.html.haml
%h1
	= @location.name
%br
%h2
	= @location.area
%p
	= @location.description
- if @location.camping == true
	this area has camping
%br
= link_to "edit this location", edit_location_path
= link_to "delete this location", location_path, :method => "delete"

app/views/routes/_routes.html.haml
=f.label :name
=f.text_field :name
%br
V
=f.select :grade, options_for_select([[0, 0],[1, 1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10],[11, 11],[12,12],[13,13],[14,14],[15,15]])

=f.select :modifier, options_for_select([[" ", 0],["+",1],["-", 2]])
%br
location
%br
= f.select :location_id, Location.all.collect {|u| [u.name, u.id]}

%br
=f.label :beta
%br
=f.text_area :beta
%br
=f.submit

app/views/routes/edit.html.haml
= form_for @route, url: route_path do |f|
	= render "routes", f: f

app/views/routes/index.html.haml
.container
	%table.table-striped
		%th name
		%th grade
		%th score
		- @routes.each do |r|
			%tr
				%td
					-if r.name
						= link_to "#{r.name}", route_path(r)
					-else
						= link_to "no name", route_path(r) 
				%td		
					= grade_format(r.grade,r.modifier)
				%td
					=r.score

	=link_to "add a route", new_route_path
		

app/views/routes/new.html.haml
= form_for @new_route, url: routes_path do |f|
	= render "routes", f: f

app/views/routes/show.html.haml
%h1
	= @route.name

%h2
	= grade_format(@route.grade,@route.modifier)
%p

	= @route.score

= link_to "edit this route", edit_route_path
= link_to "delete this route", route_path, :method => "delete"

app/views/users/index.html.haml
.container
  - @users.each do |d|
    .col-sm-4.col-xs-6 
      .panel.panel-default
        .panel-thumbnail

          = image_tag d.user_photo.url ,:style => "max-width: 100%"

        .panel-body
          %p.lead 
          Name
          = d.name
          %p
          About:
          = d.about
          %p


           

app/views/users/new.html.haml
.container
	= form_for @new_user, url: users_path, method: :post do |f|
		Name:
		%br
		= f.text_field :name
		%br
		About:
		%br
		= f.text_area :about
		%br
		Email: (this will be used for log in)
		%br
		= f.email_field :contact
		%br
		Password
		%br
		= f.password_field :password
		%br
		Password Confirmation
		%br
		= f.password_field :password_confirmation
		%br
		Upload an image
		%br
		=f.file_field :user_photo
		%br
		=f.submit "Sign up"

app/views/users/show.html.haml
.container
	.col-sm-4.col-xs-6 
		%h1
			= @user.name
		%br
		= image_tag @user.user_photo.url ,:style => "max-width: 100%"
		%h2
			= @user.about
		%p
			= @user.total_score
		%br
			

	.col-sm-4.col-xs-6 
		%h2 scores
		Your life time score
		= @attempts.sum(:attempt_score)
		%br
		this years score
		= @attempts.this_year.sum(:attempt_score)
		%br
		this months score
		= @attempts.this_month.sum(:attempt_score)
		%br
		this weeks score
		= @attempts.this_week.sum(:attempt_score)
		%br
		todays score
		= @attempts.this_day.sum(:attempt_score)


	%br
	=link_to "add an attempt", new_attempt_path
	%table.table-bordered
		%th date
		%th attempt score
		%th notes
		%th route name
		%th route grade

		 
		- @attempts.each do |f|
			%tr
				%td
					=formatted_date(f.date_attempted)
				%td
					=f.attempt_score
				%td
					=f.notes
				%td
					-if f.route
						=f.route.name
					-else
						route not found
				%td
					-if f.route
						/ =f.route.grade_format(f.route.grade,f.route.modifier)
						V
						= f.route.grade
						= f.route.modifier
					-else
						grade not found